ansible-navigator run ../playbooks/snow_change_request_wait.yml \
  --eei quay.io/rh_ee_baddicks/snow-ee \
  --penv CONTROLLER_HOST \
  --penv CONTROLLER_USERNAME \
  --penv CONTROLLER_PASSWORD \
  --penv CONTROLLER_VALIDATE_CERTS \
  --penv VMWARE_HOST \
  --penv VMWARE_USER \
  --penv VMWARE_PASSWORD \
  --penv ANSIBLE_SSH_USERNAME \
  --penv ANSIBLE_SSH_PRIVATE_KEY \
  --penv QUAY_HOST \
  --penv QUAY_PASSWORD \
  --penv QUAY_USERNAME \
  --penv ONEAGENT_ENVIRONMENT_URL \
  --penv ONEAGENT_PAAS_TOKEN \
  --penv SN_HOST \
  --penv SN_USERNAME \
  --penv SN_PASSWORD \
  --penv RHC_ORGANIZATION \
  -i ../inventory.yml
#   -m stdout \