---
- name: Update all packages
  hosts: "{{ snow_configuration_item | default('webservers') }}"
  gather_facts: false

  tasks:
    - name: Update all installed packages
      ansible.builtin.package:
        name: '*'
        state: latest
      become: true
      register: package_results

    - ansible.builtin.set_stats:
        data:
          snow_work_notes: "{{ package_results.results | to_nice_yaml }}"
          package_results_count: "{{ package_results.results | length }}"
          snow_request_state: closed_complete
          snow_ticket_number: "{{ snow_ticket_number | default('111111') }}"
          snow_hostname: "{{ snow_hostname | default('eda-web1') }}"
          snow_snapshot: "{{ snow_snapshot | default(false) }}"




