---
- name: Update all packages
  hosts: "{{ snow_configuration_item | default('webservers') }}"
  gather_facts: false

  tasks:
    - name: Set package state
      when: snow_implementation_plan is defined
      ansible.builtin.set_fact:
        package_state: present

    - name: Update requested packages
      ansible.builtin.package:
        name: "{{ snow_implementation_plan[inventory_hostname].installed | default('*') }}"
        state: "{{ package_state | default(latest) }}"
      become: true
      register: package_results

    - name: Set stats for subsequent Job Templates
      ansible.builtin.set_stats:
        data:
          # package_results_count: "{{ package_results.results | length }}"
          # snow_request_state: closed_complete
          # snow_ticket_number: "{{ snow_ticket_number | default('111111') }}"
          # snow_hostname: "{{ snow_hostname | default('eda-web1') }}"
          # snow_snapshot: "{{ snow_snapshot | default(false) }}"
          snow_implementation_plan: "{{ lookup('template', '../templates/implementation_plan.j2') }}"
