---
- name: Update all packages
  hosts: "{{ snow_configuration_item | default('webservers') }}"
  gather_facts: false

  tasks:
    - name: Implmentation Plan defined
      when: implementation_plan is defined
      block:
        - name: Set package state
          ansible.builtin.set_fact:
            package_state: present

        - name: Update requested packages
          ansible.builtin.package:
            name: "{{ implementation_plan.installed | default('*') }}"
            state: "{{ package_state | default('latest') }}"
          become: true
          register: package_results

        - name: Set facts for next SNOW update
          ansible.builtin.set_fact:
            ctask_work_notes: |
              Patching results:

              {{ package_results.results }}
            ctask_update: true
            cacheable: true

    - name: Implmentation Plan is not defined
      when: implementation_plan is not defined
      block:
        - name: Get package information
          ansible.builtin.package:
            name: "*"
            state: "latest"
          become: true
          register: package_results

        - name: Set stats for subsequent Job Templates
          ansible.builtin.set_stats:
            data:
              snow_implementation_plan: "{{ lookup('template', '../templates/implementation_plan.j2') }}"
