---
- name: Update all packages
  hosts: webservers
  gather_facts: false

  tasks:
    - name: Update all installed packages
      ansible.builtin.package:
        name: '*'
        state: latest
      become: true

    - debug:
        var: check_mode
