---
- name: Update all packages
  hosts: "{{ snow_configuration_item | default('webservers') }}"
  gather_facts: false

  tasks:
    - name: Implmentation Plan is not defined
      when: implementation_plan is not defined or
            implementation_plan | length == 0
      block:
        - name: Get package information
          ansible.builtin.package:
            name: "*"
            state: "latest"
          become: true
          register: package_results

        - name: Set stats for subsequent Job Templates
          ansible.builtin.set_stats:
            data:
              snow_implementation_plan: "{{ lookup('template', '../templates/implementation_plan.j2') }}"

    - name: Implmentation Plan defined
      when:
        - implementation_plan is defined
        - implementation_plan | length > 0
      block:
        - name: Set package state
          ansible.builtin.set_fact:
            package_state: present

        - name: Update requested packages
          ansible.builtin.package:
            name: "{{ implementation_plan.installed | default('*') }}"
            state: "{{ package_state | default('latest') }}"
          become: true
          register: package_results

        - name: Set package output when length > 0
          when: package_results.results | length > 0
          ansible.builtin.set_fact:
            package_output: "{{ package_results.results | to_nice_yaml }}"

        - name: Set package output when length = 0
          when: package_results.results | length == 0
          ansible.builtin.set_fact:
            package_output: "No packages to update."

        - name: Set facts for next SNOW update
          ansible.builtin.set_fact:
            ctask_work_notes: |
              Patching results:

              {{ package_output }}
            ctask_update: true
            ctask_state: closed
            ctask_close_notes: "Patching complete."
            ctask_close_code: successful
            crequest_update: true
            crequest_state: review
            # crequest_close_notes: "Patching complete."
            # crequest_close_code: successful
            implementation_plan: ''
            cacheable: true