---
- name: Update Catalog Request
  hosts: "{{ snow_configuration_item | default('snow') }}"
  gather_facts: false

  tasks:
  # - name: Update to implement the change request in ServiceNow
  #   servicenow.itsm.change_request:
  #     state: "{{ change_request_number_state }}"
  #     number: "{{ snow_cr_number }}"
  #     assignment_group: "{{ snow_cr_assignment_group }}"
  #   delegate_to: localhost

  - name: Update SNOW Change Request
    when:
      - crequest_update is defined
      - crequest_update
    servicenow.itsm.change_request:
      state: "{{ crequest_state | default(omit, true) }}"
      close_notes: "{{ crequest_close_notes | default(omit, true) }}"
      close_code: "{{ crequest_close_code | default(omit, true) }}"
      number: "{{ snow_cr_number }}"
    delegate_to: snow
    run_once: true

  - name: Update SNOW Change Task
    when:
      - ctask_update is defined
      - ctask_update
    servicenow.itsm.change_request_task:
      state: "{{ ctask_state | default(omit, true) }}"
      close_notes: "{{ ctask_close_notes | default(omit, true) }}"
      close_code: "{{ ctask_close_code | default(omit, true) }}"
      number: "{{ ctask }}"
      other:
        work_notes: "{{ ctask_work_notes | default(omit, true) }}"
    delegate_to: snow

  - name: Clear updates
    ansible.builtin.set_fact:
      ctask_update: false
      ctask_state: null
      ctask_work_notes: null
      ctask_close_notes: null
      ctask_close_code: null
      crequest_update: false
      crequest_state: null
      crequest_close_notes: null
      crequest_close_code: null
      cacheable: true
