---
- name: Get info from SNOW CR
  hosts: snow
  gather_facts: false
  vars:
    snow_cr_number: CHG0030538

  tasks:
    - name: Retrieve SNOW Change Request info
      servicenow.itsm.change_request_info:
        number: "{{ snow_cr_number }}"
      register: snow_cr_request_info

    - name: Retrieve SNOW Change Task info
      servicenow.itsm.change_request_task_info:
        query:
          - change_request: "= {{ snow_cr_request_info.records[0].sys_id }}"
        sysparm_display_value: true
      register: snow_cr_task_info

    - name: Set facts for each hosts
      ansible.builtin.set_fact:
        implementation_plan: "{{ item.description | ansible.builtin.from_yaml }}"
        ctask: "{{ item.number }}"
        ctask_work_notes: "{{ (item.description | ansible.builtin.from_yaml).take_snapshot | ansible.builtin.ternary('Starting VMWare snapshot.','Skipping VMWare snapshot.') }}"
        ctask_state: in_progress
        ctask_update: true
        cacheable: true
      delegate_to: "{{ item.cmdb_ci }}"
      delegate_facts: true
      loop: "{{ snow_cr_task_info.records }}"

    - name: Set stats for subsequent playbooks
      ansible.builtin.set_stats:
        data:
          snow_configuration_item: "{{ snow_cr_task_info.records | map(attribute='cmdb_ci') }}"

