---
- name: Update Catalog Request
  hosts: snow
  gather_facts: false

  tasks:
    - name: Retrieve catalog request sysid
      servicenow.itsm.api_info:
        resource: sc_request
        sysparm_query: numberSTARTSWITH{{ snow_ticket_number }}
      register: requestresult
      when: snow_ticket_number != ''

    - name: Update a catalog work notes and state in ServiceNow
      servicenow.itsm.api:
        action: patch
        resource: sc_request
        sys_id: "{{ requestresult.record[0].sys_id }}"
        data:
          request_state: "{{ request_state | default(omit) }}"
          work_notes: "{{ stat_package_results }}"
      when:
        - snow_ticket_number != ''
        - requestresult.record[0].sys_id is defined