---
- name: Get info from SNOW CR
  hosts: snow
  gather_facts: false

  tasks:
    - name: Block to create CR
      block:

        - name: Retrieve SNOW Change Request info
          servicenow.itsm.change_request_info:
            number: "{{ snow_cr_number }}"
          register: snow_cr_request_info
          delegate_to: localhost

        - name: Set stats for subsequent Job Templates
          ansible.builtin.set_stats:
            data:
              snow_implementation_plan: "{{ snow_cr_request_info.records[0] | ansible.builtin.from_yaml }}"