---
- name: Setup Ansible components
  hosts: snow
  gather_facts: false

  tasks:
    - name: Block to create CR
      block:
        - name: Create ServiceNow Change Request
          servicenow.itsm.change_request:
            type: normal
            short_description: "{{ snow_cr_short_description }}"
            description: "{{ snow_cr_description }}"
            priority: high
            risk: moderate
            impact: low
            assignment_group: "{{ snow_cr_assignment_group }}"
            state: assess
          register: snow_cr_request
          until: snow_cr_request.changed is defined
          retries: 5
          delay: 5
          delegate_to: localhost

        # - name: Pass along request information
        #   ansible.builtin.set_stats:
        #     data:
        #       request: "{{ request }}"
        #     per_host: false
        #   delegate_to: localhost

        # - name: Send Approval e-mail
        #   community.general.mail:
        #     host: "{{ EMAIL_HOST }}"
        #     username: "{{ EMAIL_USERNAME }}"
        #     password: "{{ EMAIL_PASSWORD }}"
        #     port: "{{ EMAIL_PORT }}"
        #     subject: Approval request for ServiceNow Change Request {{ request.record.number }}
        #     body: "You have a new CR Approval request. Please click on this URL to approve: {{ lookup('env', 'SN_HOST') }}nav_to.do?uri=change_request.do?sysparm_query=number={{
        #       request.record.number }}"
        #     from: tower@shadowman.dev
        #     to: "{{ to_email }}"
        #   delegate_to: localhost

        - name: Wait for Change Request approval
          servicenow.itsm.change_request_info:
            number: "{{ snow_cr_request.record.number }}"
          until: snow_cr_request_status.records[0].state == "authorize"
          retries: 50
          delay: 10
          register: snow_cr_request_status
          delegate_to: localhost

        # - name: Update to implement the change request in ServiceNow
        #   servicenow.itsm.change_request:
        #     state: implement
        #     number: "{{ snow_cr_request.record.number }}"
        #     assignment_group: "{{ snow_cr_assignment_group }}"
        #   delegate_to: localhost