---
- name: Get info from SNOW CR
  hosts: snow
  gather_facts: false

  tasks:
    - name: Retrieve SNOW Change Request info
      servicenow.itsm.change_request_info:
        number: "{{ snow_cr_number }}"
      register: snow_cr_request_info

    - name: Retrieve SNOW Change Task info
      servicenow.itsm.change_request_info:
        query:
          - change_request: "= {{ snow_cr_request_info.records[0].sys_id }}"
      register: snow_cr_task_info


        # - name: Set stats for subsequent Job Templates
        #   ansible.builtin.set_stats:
        #     data:
        #       snow_implementation_plan: "{{ snow_cr_request_info.records[0].implementation_plan | ansible.builtin.from_yaml }}"