---
- name: Update Catalog Request
  hosts: snow
  gather_facts: false

  tasks:
  - name: Update to implement the change request in ServiceNow
    servicenow.itsm.change_request:
      state: "{{ change_request_number_state }}"
      number: "{{ snow_cr_number }}"
      assignment_group: "{{ snow_cr_assignment_group }}"
    delegate_to: localhost