---
- name: Add 4 hours to the planned datetime
  hosts: localhost
  # vars:
  #   snow_planned_datetime: "2024-09-11 10:02:30"  # Original datetime
  #   snow_configuration_item:
  #     - eda-web1
  #     - eda-web2
  tasks:
    - ansible.builtin.set_fact:
        utc_year: "{{ (snow_planned_datetime | to_datetime).year }}"
        utc_month: '{{ "%02d" | format((snow_planned_datetime | to_datetime).month) }}'
        utc_day: '{{ "%02d" | format((snow_planned_datetime | to_datetime).day) }}'
        utc_hour: '{{ "%02d" | format((snow_planned_datetime | to_datetime).hour | int +4) }}'
        utc_minute: '{{ "%02d" | format((snow_planned_datetime | to_datetime).minute | int) }}'

    - ansible.builtin.set_fact:
        utc_planned_datetime: >-
          {{ utc_year }}-{{ utc_month }}-{{ utc_day }}
          {{ utc_hour }}:{{ utc_minute }}:00

    - debug:
        var: utc_planned_datetime

    - set_fact:
        ci_map: "{{ ci_map | default([]) + [dict(name=item[0], sysid=item[1])] }}"
      loop: "{{ snow_configuration_item | zip(snow_configuration_sysid) | list }}"

    - debug:
        var: ci_map
