---
- name: Take snapshot if required
  hosts: "{{ snow_configuration_item | default('vcenter') }}"
  gather_facts: false
  vars:
    - vcenter_creds: &vcenter_conn
        hostname: "{{ lookup('ansible.builtin.env', 'VMWARE_HOST') }}"
        username: "{{ lookup('ansible.builtin.env', 'VMWARE_USER') }}"
        password: "{{ lookup('ansible.builtin.env', 'VMWARE_PASSWORD') }}"

  tasks:
    - name: Tasks when snapshot requested
      when: implementation_plan.take_snapshot
      block:
        - name: Create snapshot
          ansible.builtin.debug:
            msg: "take snapshot"

        - name: Update to implement the change request in ServiceNow
          servicenow.itsm.change_request_task:
            state: in_progress'
            number: "{{ ctask }}"
            other:
              work_notes: "Starting VMWare snapshot"
          delegate_to: snow

        - name: Create a snapshot
          community.vmware.vmware_guest_snapshot:
            <<: *vcenter_conn
            datacenter: "{{ vcenter_datacenter }}"
            folder: "/{{ vcenter_datacenter }}/vm/{{ vcenter_vm_folder | default(omit) }}"
            name: "{{ inventory_hostname }}"
            state: present
            snapshot_name: "{{ snow_cr_number }}{{ ctask }}"
            description: pre-patching
          delegate_to: vcenter
          register: vcenter_snapshot_info